{
 "title": "cello",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host_ip", "query": { "query": "label_values(host_ip)" } },
   {
    "name": "cello_gen",
    "query": {
     "query": "label_values(label_pod_template_generation)"
    }
   },
   { "name": "node", "query": { "query": "label_values(host_ip)" } },
   {
    "name": "resType",
    "query": {
     "query": "label_values(resource_pool_target, type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "rpc_latency_ms",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(rpc_latency_ms_sum{host_ip=~\"$host_ip\"}[5m])) by (host_ip, rpc_api) / sum(rate(rpc_latency_ms_count{host_ip=~\"$host_ip\"}[5m])) by (host_ip, rpc_api)",
       "legendFormat": "{{host_ip, rpc_api}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OpenAPI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Openapi qps(sum)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(openapi_latency_ms_count{}[2m])) by (api)",
       "legendFormat": "{{tag_api}}"
      }
     ]
    },
    {
     "title": "Openapi qps(error)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(openapi_latency_ms_count{error=~\"true\"}[5m])) by (api, code)",
       "legendFormat": "{{api, code}}"
      }
     ]
    },
    {
     "title": "Openapi qps(FlowLimit)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(openapi_latency_ms_count{code=~\"FlowLimitExceeded|AccountFlowLimitExceeded\"}[2m])) by (api)",
       "legendFormat": "{{tag_api}}"
      }
     ]
    },
    {
     "title": "openapi_latency_ms Overall",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(openapi_latency_ms_sum{host_ip=~\"$host_ip\"}[5m])) by(host_ip) / sum(rate(openapi_latency_ms_count{host_ip=~\"$host_ip\"}[5m])) by(host_ip)",
       "legendFormat": "{{host_ip}}"
      }
     ]
    },
    {
     "title": "openapi latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(openapi_latency_ms_sum{host_ip=~\"$host_ip\"}[5m])) by (host_ip, api) / sum(rate(openapi_latency_ms_count{host_ip=~\"$host_ip\"}[5m])) by (host_ip, api)",
       "legendFormat": "{{host_ip, api}}"
      }
     ]
    },
    {
     "title": "openapi error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum(openapi_error_count{host_ip=~\"$host_ip\",label_pod_template_generation=~\"$cello_gen\"}) by (host_ip, api, code)",
       "legendFormat": "{{host_ip, api, code}}"
      }
     ]
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Metadata qps(sum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metadata_latency_ms_count{}[2m])) by (metadata)",
     "legendFormat": "{{tag_metadata}}"
    }
   ]
  },
  {
   "title": "Metadata qps(error)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metadata_latency_ms_count{error=~\"true\"}[5m])) by (metadata)",
     "legendFormat": "{{metada}}"
    }
   ]
  },
  {
   "title": "metadata error",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(metadata_error_count{host_ip=~\"$host_ip\",label_pod_template_generation=~\"$cello_gen\"}) by (host_ip, metadata)",
     "legendFormat": "{{host_ip, metadata}}"
    }
   ]
  },
  {
   "title": "metadata_latency_ms Overall",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metadata_latency_ms_sum{host_ip=~\"$host_ip\"}[5m])) by(host_ip) / sum(rate(metadata_latency_ms_count{host_ip=~\"$host_ip\"}[5m])) by(host_ip)",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "metadata latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(metadata_latency_ms_sum{host_ip=~\"$host_ip\"}[5m])) by (host_ip, metadata) / sum(rate(metadata_latency_ms_count{host_ip=~\"$host_ip\"}[5m])) by (host_ip, metadata)",
     "legendFormat": "{{host_ip, metadata}}"
    }
   ]
  },
  { "title": "IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Pool  Config",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_pool_max_cap{host_ip=~\"$node\", type=\"$resType\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "resource_pool_target{host_ip=~\"$node\", type=\"$resType\"}",
     "legendFormat": "Target"
    },
    {
     "expr": "resource_pool_target_min{host_ip=~\"$node\", type=\"$resType\"}",
     "legendFormat": "TargetMin"
    }
   ]
  },
  {
   "title": "Pool  Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_pool_total{host_ip=~\"$node\", type=\"$resType\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "resource_pool_available{host_ip=~\"$node\", type=\"$resType\"}",
     "legendFormat": "Available"
    }
   ]
  }
 ]
}