# https://developer.volcengine.com/articles/7132385421970915358
- name: Add an apt signing key for Kubernetes
  apt_key:
    url: http://mirrors.ivolces.com/kubernetes/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb http://mirrors.ivolces.com/kubernetes/apt/ kubernetes-xenial main
    state: present
    filename: /etc/apt/sources.list.d/kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    force_apt_get: yes
  vars:
    packages:
      - kubelet=1.24.10-00
      - kubeadm=1.24.10-00
      - kubectl=1.24.10-00
  notify:
    - kubelet status

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ inventory_hostname }}
    state: present
    create: yes
  register: kubelet_config

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
  when: kubelet_config.changed
